# Generated by Django 5.1.1 on 2024-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
