# Generated by Django 5.1.1 on 2024-09-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_subtitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitles',
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
