# Generated by Django 5.1.1 on 2024-09-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_remove_video_subtitles_video_subtitle_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=50)),
                ('subtitle_text', models.TextField()),
                ('timestamp_in_seconds', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='video_app.video')),
            ],
        ),
    ]
